source 'https://github.com/CocoaPods/Specs.git'

target 'PriorityScheduler', :exclusive => true do
  pod "PrioritySchedulerPod", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PrioritySchedulerPod", :path => "../"
end
